apiVersion: v1
kind: Namespace
metadata:
  name: opdracht-3
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: opdracht-3
  labels:
    app: nginx
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: opdracht-3
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: opdracht-3
spec:
  rules:
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80

